services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  godot-server-1:
    build:
      context: .
      dockerfile: Dockerfile.godot
      args:
        SERVER_PORT: 12341
    environment:
      SERVER_PORT: 12341
      SERVER_EXE: server.console.exe
    ports:
      - "12341:12341"

  godot-server-2:
    build:
      context: .
      dockerfile: Dockerfile.godot
      args:
        SERVER_PORT: 12342
    environment:
      SERVER_PORT: 12342
      SERVER_EXE: server2.console.exe
    ports:
      - "12342:12342"

  godot-server-3:
    build:
      context: .
      dockerfile: Dockerfile.godot
      args:
        SERVER_PORT: 12343
    environment:
      SERVER_PORT: 12343
      SERVER_EXE: 2v2_server.console.exe
    ports:
      - "12343:12343"
volumes:
  pgdata: